apiVersion: redis.kun/v1alpha1
kind: DistributedRedisCluster
metadata:
  annotations:
    # if your operator run as cluster-scoped, add this annotations
    redis.kun/scope: cluster-scoped
  name: example-distributedrediscluster
spec:
  image: redis:5.0.4-alpine
  masterSize: 3
  clusterReplicas: 1
  config:
    activerehashing: "yes"
    appendfsync: everysec
    appendonly: "yes"
    hash-max-ziplist-entries: "512"
    hash-max-ziplist-value: "64"
    hll-sparse-max-bytes: "3000"
    list-compress-depth: "0"
    maxmemory-policy: noeviction
    maxmemory-samples: "5"
    no-appendfsync-on-rewrite: "no"
    notify-keyspace-events: ""
    set-max-intset-entries: "512"
    slowlog-log-slower-than: "10000"
    slowlog-max-len: "128"
    stop-writes-on-bgsave-error: "yes"
    tcp-keepalive: "0"
    timeout: "0"
    zset-max-ziplist-entries: "128"
    zset-max-ziplist-value: "64"
